fuzz: Remove unused g_setup pointers
These are unused and removing them avoids clang warnings like:

src/test/fuzz/deserialize.cpp:42:26: error: variable g_setup set but not used [-Werror,-Wunused-but-set-variable]

Github-Pull: #34918
Rebased-From: fabbfec3b00c138a28034a4f5594305d2220b9bb